# Generated by Django 5.1.2 on 2024-10-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="email",
            new_name="email1",
        ),
    ]
