# Generated by Django 5.1.2 on 2024-10-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_rename_email_profile_email1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="email1",
            new_name="email",
        ),
    ]
