# Generated by Django 5.0.2 on 2024-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=False, max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
