# Generated by Django 5.1.2 on 2024-10-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="activity_images/"
                    ),
                ),
                ("is_favorited", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("sponsor", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sponsorship_images/"
                    ),
                ),
                ("date_posted", models.DateField(auto_now_add=True)),
                ("is_favorited", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
