# Generated by Django 5.1.2 on 2024-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activitynew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="activitynew_images/"
                    ),
                ),
                ("is_favorited", models.BooleanField(default=False)),
            ],
        ),
    ]
