# Generated by Django 5.1.2 on 2024-10-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_activity_sponsorship_delete_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorship",
            name="location",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
