# Generated by Django 5.1.2 on 2024-11-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_sponsorshipnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Sponsorship',
        ),
    ]
