# Generated by Django 4.2.16 on 2024-11-14 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_activity_delete_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipnew',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activitynew',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
