# Generated by Django 5.1.2 on 2024-11-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_sponsorshipnew_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitynew",
            name="check_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sponsorshipnew",
            name="check_status",
            field=models.BooleanField(default=False),
        ),
    ]
