# Generated by Django 4.2.16 on 2024-11-17 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_sponsorshipnew_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipnew',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
