# Generated by Django 5.0.2 on 2024-11-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="user_photos/default.jpg",
                null=True,
                upload_to="user_photos/",
            ),
        ),
    ]
