# Generated by Django 5.1.3 on 2024-11-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynew',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sponsorshipnew',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
