# Generated by Django 5.1.3 on 2024-11-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynew',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='activitynew',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='經度'),
        ),
        migrations.AlterField(
            model_name='activitynew',
            name='location',
            field=models.CharField(max_length=255, verbose_name='活動地點'),
        ),
    ]
