# Generated by Django 5.1.3 on 2024-11-29 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_activitynew_latitude_activitynew_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.sponsorshipnew'),
        ),
    ]
