# Generated by Django 5.1.3 on 2024-11-29 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_notification_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.activitynew'),
        ),
    ]
