# Generated by Django 5.1.2 on 2024-11-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_alter_notification_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitynew",
            name="registration_deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
