# Generated by Django 5.1.2 on 2024-11-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_sponsorshipnew_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitynew",
            name="max_participants",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
