# Generated by Django 5.1.2 on 2024-12-02 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_activitynew_current_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipnew",
            name="item",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AddField(
            model_name="sponsorshipnew",
            name="people",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AlterField(
            model_name="sponsorshipnew",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipnew",
            name="location",
            field=models.CharField(default=" ", max_length=100),
        ),
    ]
