# Generated by Django 5.1.2 on 2024-12-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_sponsorshipnew_item_sponsorshipnew_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipnew",
            name="people",
            field=models.TextField(default=" ", max_length=100),
        ),
    ]
