# Generated by Django 5.1.2 on 2024-12-02 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_alter_sponsorshipnew_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipnew",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
