# Generated by Django 4.2.16 on 2024-12-02 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0025_remove_activitynew_is_favorited_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'activity')},
        ),
        migrations.AddField(
            model_name='favorite',
            name='sponsorship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.sponsorshipnew'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.activitynew'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'sponsorship'), ('user', 'activity')},
        ),
    ]
