# Generated by Django 4.2.16 on 2024-12-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_favorite_unique_together_favorite_sponsorship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitynew',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorshipnew',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
