# Generated by Django 5.1.2 on 2024-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0027_activitynew_is_favorited_sponsorshipnew_is_favorited_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitynew",
            name="image",
            field=models.ImageField(
                blank=True, default="01.jpg", null=True, upload_to="activitynew_images/"
            ),
        ),
    ]
