# Generated by Django 5.1.2 on 2024-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_alter_activitynew_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitynew",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="activitynew_images/"
            ),
        ),
    ]
