# Generated by Django 4.2.16 on 2024-12-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_activitynew_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_club',
            field=models.BooleanField(default=False),
        ),
    ]
