# Generated by Django 4.2.16 on 2024-12-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_activitynew_date_posted'),
        ('events', '0031_remove_userprofile_is_brand_and_more'),
    ]

    operations = [
    ]
