# Generated by Django 5.1.2 on 2024-12-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0032_merge_20241203_0127"),
        ("events", "0032_merge_20241203_0130"),
    ]

    operations = []
