# Generated by Django 4.2.16 on 2024-12-02 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0033_merge_20241203_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitynew',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='sponsorshipnew',
            name='is_favorited',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.activitynew')),
                ('sponsorship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.sponsorshipnew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity'), ('user', 'sponsorship')},
            },
        ),
    ]
